In [1]:
import numpy as np
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.20991029,  0.33272123,  0.00752667, -0.12588485, -0.19633475,
        -0.68433213,  0.04164742,  0.10261737,  0.5012409 , -0.42583132]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.08208819, 0.14123507, 0.10202635, 0.08928376, 0.08321018,
        0.05107894, 0.10556764, 0.11220436, 0.16715898, 0.06614657]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.974383

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2967 - accuracy: 0.9148

In [11]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0775 - accuracy: 0.9769


[0.07747869193553925, 0.9768999814987183]

In [12]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [13]:
prob_predict = probability_model(x_test[:5])

In [14]:
import numpy as np
np.argmax(prob_predict, axis=1)

array([7, 2, 1, 0, 4])

In [15]:
y_test[:5]

array([7, 2, 1, 0, 4], dtype=uint8)