In [1]:
import numpy as np
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [3]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [5]:
x_train[:20].shape

(20, 28, 28)

In [6]:
predictions = model(x_train[:20]).numpy()

In [7]:
np.argmax(tf.nn.softmax(predictions).numpy(), axis=1)

array([9, 5, 9, 6, 6, 6, 3, 9, 3, 6, 5, 7, 9, 6, 9, 6, 5, 6, 6, 3])

In [8]:
y_train[:20]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9],
      dtype=uint8)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions[:1]).numpy()

2.1522112

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 679us/step - loss: 0.3028 - accuracy: 0.9121

In [13]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0817 - accuracy: 0.9748


[0.08174936473369598, 0.9747999906539917]

In [14]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [15]:
np.argmax(probability_model(x_test[:5]), axis=1)

array([7, 2, 1, 0, 4])

In [16]:
y_test[:5]

array([7, 2, 1, 0, 4], dtype=uint8)